version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: geo-pagos-mysql
      working_dir: /application
      volumes:
        - ./:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=geo_pagos_user
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "1027:3306"

    webserver:
      image: nginx:alpine
      container_name: geo-pagos-webserver
      working_dir: /application
      volumes:
          - ./:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: geo-pagos-php-fpm
      working_dir: /application
      volumes:
        - ./:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

