<?php

namespace AppBundle\Repository;

/**
 * UsuarioPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
